language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - ./travis-create-config.sh

script:
  - vendor/bin/phpunit
